export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_ERROR = "PRODUCT_ERROR";

export const CART_NEW = "CART_NEW";
export const CART_ADD = "CART_ADD";
export const CART_REMOVE = "CART_REMOVE";
export const CART_ADD_QUANTITY = "CART_ADD_QUANTITY";
export const CART_ORDER_SAVED = "CART_ORDER_SAVED";
export const CART_CHECKOUT = "CART_CHECKOUT";
export const CART_CHECKOUT_ERROR = "CART_CHECKOUT_ERROR";

export const ALERT_SHOW = "ALERT_SHOW";
export const ALERT_HIDE = "ALERT_HIDE";
